features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://2015 Janeiro 12 PhotoScape Brush Cat preto.png'
favicon:
  use_default: true
